# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4180f34
_src_path: gh:scipp/copier_template
description: Python application craft helper tools.
max_python: '3.12'
min_python: '3.10'
namespace_package: ''
nightly_deps: ''
orgname: scipp
prettyname: App Crafter
projectname: app-crafter
related_projects: ''
year: 2024
